<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <!-- Directory containing VapourSynth4.h and VSHelper4.h; override with /p:VapourSynthIncludeDir=... -->
    <VapourSynthIncludeDir Condition="'$(VapourSynthIncludeDir)'==''">C:\Program Files\VapourSynth\sdk\include\vapoursynth</VapourSynthIncludeDir>
  </PropertyGroup>
  <PropertyGroup>
    <TargetExt>.dll</TargetExt>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(VapourSynthIncludeDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="VapourSynthIncludeDir">
      <Value>$(VapourSynthIncludeDir)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>
